---
- name: Install Common Packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - amazon-efs-utils
    - awscli
    - curl
    - git
    - unzip
    - procps-ng
    - wget

- name: Cleanup artifacts
  block:
    - name: Clean yum
      command: yum clean all
        warn=False
      changed_when: False

    - name: Remove yum cache
      file:
        state: absent
        path: /var/cache/yum

    - name: Remove all tmp files
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /tmp/*
        - /var/tmp/*
