Vagrant.configure("2") do |config|
    config.vm.box = "winky/amazonlinux-2"
    config.vm.provision "file",
      source: "~/.ssh/id_rsa.pub",
      destination: "~/.ssh/authorized_keys"
  
    config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 2048
      v.cpus = 2
    end
  
    config.vm.define :machine0 do |config|
      config.vm.network "private_network", ip: "192.168.50.5"
    end
  end
